# print("WELCOME TO ATM")
# card=input("please insert your card,debit card or credit card")
# if card=="credit card" or card=="debit card":
#     print("after")
#     language=input("please select your language,hindi or english")
#     if language=="english":
#         print("tell")
#         pin=int(input("enter any 4 digite number"))
#         if 9999>=pin:
#             print("please wait")
#             service=input("please chose a service deposite,balance enquairy or cash withdral")
#             if service=="balance enquairy" or service=="cash withdral":
#                 print("cash withdral")
#                 money=int(input("check your total "))
#                 if ("10000>=money"):
#                     print("conform")
#                     recipt=input("please wait transaction is proceeding,proceed or faild")
#                     if recipt=="faild" or recipt=='proceed':
#                         print("proceed")
#                         print("thankyou")
#                     else:
#                         ("transaction is faild")
#                 else:
#                     print("more then 10000 thousend")
#             else:
#                 print("not velid")
#         else:
#             print("invalid")
#     # language=input("bhasa ko chune")
#     elif language=="hindi":
#         print('kaho')
#         seba=input("seba ko chune")
#         if seba=="balance enquairy" or seba=="cash withdrowal":
#            print("cash withdrowal")
#            money=int(input("check your total "))
#            if ("10000>=money"):
#                print("intejar kre")
#                pin=int(input("koi bhi 4 aunk dale"))
#                if pin<=9999:
#                    print("entejar kre")
#                    account=input("account ko chune")
#                    if account=="bachat khata" or account=="chalu khata":
#                        print("bachat khate ke sath continue kre")
#                        service=input("kirpiya seva ko chune")
#                        if service=="balance equairy" or service=="cash withdral":
#                            print("cash withdral")
#                            recipt=input("please wait transaction is proceeding")
#                            if recipt=="accept" or recipt=="faild":
#                                print("accept")
#                                print("THANKYOU")
#                            else:
#                                print("faile")
#                        else:
#                            print("galat information")
#                    else:
#                         print("not vaild")
#                else:
#                    print("galat pin hai")
#            else:
#                print("10000 se jada hai")
#         else:
#             print("worng information")
#     else:
#         print("shi ni hai")
# else:
#     print("try again")
                               
                            
                                

                          


   