# 1.DEBUGGING

# year=2016
# name="navgurukul"
# print(name+','+str(year)+  "main start hua tha")


# 2.DEBUGGING

# Save the correct code in a new file and submit it.

# price_milk=int(input("1L milk ka price dallo?"))
# print(10L milk+price_milk*10"+"rupees ka aata hai")



# 3. Save the correct code in a new file and submit it.

# number=input("please enter a decimal number")
# print("your number divided by 2 is equal to=  +number/2")



# 4. Save the correct code in a new file and submit it

# mangoes=5
# manGoes=mangoes+5
# print("10/5")



