print("WELCOME")
print("CREATE AN ACCOUNT")
create=input("create a new account")
# if create=="yes":
#     print("new account")
#     name=input("enter first name")
#     if name>="a" and name<="z":
#         print("name")
#         lastname=input("enter second name")
#         if lastname>="a" and lastname<="z":
#             print("surname")
#             email=input("enter the email")
#             if email>="a@gmail.com" and email<="z@gmail.com":
#                 print("email")
#                 ph_num=int(input("enter the phon num"))
#                 if ph_num>=0:
#                     print("phon num")
#                     password=int(input("enter the password"))
#                     if password>=0:
#                         print("password")
#                         print("THANKYOU")
#                     # gender=input("enter the gender,male and female")
#                     # if gender==("male and female"):
#                     #     print("gen")
#                     # else:
#                     #     print("Error")
#                     else:
#                         print("worng password")
#                 else:
#                     print("worng num")
#             else:
#                 print("miss mach")
#         else:
#             print("earror")
#     else:
#         print("worng inforation")
# else:
#     print("no")









